version: '3'
services:
  app:
    build: ./backend
    container_name: fastapi_test_app
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  redis:
    container_name: redis-test
    image: redis:latest
    ports:
      - 6379:6379